### ISSUE TITLE
How to deal with request completion?

### ISSUE THREAD

**Issue by lordanubi** [mikeborozdin/http-streaming-request#1]
Hi first of all thanks for this awesome package! I wanted to ask you if there is a way to know when the stream is finished.
I tried something like this but of corse the returned value from newsSoFar is always parsable.

```javascript
for await (const newsSoFar of makeStreamingJsonRequest({
      url: "/generate",
      method: "POST",
    })) {
      //try to parse json if we can do that it means the response is complete
      try {
        setIsGenerating(false);
        return;
      } catch (e) {
        console.log("not complete", e);
        //if we can't parse json it means the response is not complete
      }
```

 It would be nice if that is done internally and once the request is complete a callback function is executed.
 
 Something like
```javascript
 makeStreamingJsonRequest({
      url: "/generate",
      method: "POST",
     onComplete: () => setIsGenerating(false)
    }
```

What do you think?

**Comment by mikeborozdin** [comment]
Hi @lordanubi,

Do you really need an `onComplete()`?

If we take [an example from Readme](https://github.com/mikeborozdin/http-streaming-request?tab=readme-ov-file#a-way-out).

```ts
const stream = makeStreamingJsonRequest({
  url: "/some-api",
  method: "POST",
});

for await (const data of stream) {
  // if the API only returns [{"name": "Joe
  // the line below will print `[{ name: "Joe" }]`

  console.log(data);
}
```

We can just conclude that the stream is over after `for await`.

e.g. you can do this

```ts
const stream = makeStreamingJsonRequest({
  url: "/some-api",
  method: "POST",
});

for await (const data of stream) {
  // if the API only returns [{"name": "Joe
  // the line below will print `[{ name: "Joe" }]`

  console.log(data);
}

setIsGenerating(false);
```

**Comment by lordanubi** [comment]
Yep that was much simpler than what I initially thought! Thanks a lot :)
